.gitignore
README.md

#16 
1. delete db and ignore db
2. update migration command in README

Not track app database in git

---

.travis.yml
README.md
app/app/settings.py
app/server/tests/test_annotation_api.py
app/server/tests/test_models.py
app/server/tests/test_projects_api.py

As per https://github.com/chakki-works/doccano/projects/2#card-16405325, this change supports TravisCI for the project.
This enables us to detect problems early stage.

Support Travis CI

---

app/server/static/js/.eslintrc.js
app/server/static/js/demo/demo_named_entity.js
app/server/static/js/demo/demo_translation.js
app/server/static/js/label.js
app/server/static/js/seq2seq.js
app/server/static/js/sequence_labeling.js
app/server/static/js/stats.js

This is a follow-up to https://github.com/chakki-works/doccano/pull/148 where ESlint was introduced for the Vue components. This change fixes all the lint errors at the `plugin:vue/recommended` level. No functional changes are introduced.

Enhancement/Fix all Vue ESlint errors

---

app/server/package-lock.json
app/server/package.json

Upgrade marked to version 0.3.19.
Corresponding CVE:
* [CVE-2017-16114](https://nvd.nist.gov/vuln/detail/CVE-2017-16114)

Fix security vulnerability for marked

---

app/server/serializers.py
app/server/tests/test_api.py

Solves #162.
Now possible to save the same label in other projects.

Possible to save the same label in other projects

---

app/server/static/js/projects.vue

All Vue templates in the code base except for the Projects component are written in pug, so this change makes the codebase consistent by also porting the Projects component template from html to pug. This is a pure refactor without any functional change.

Enhancement/Move projects Vue template to pug

---

app/server/static/js/download.pug
app/server/static/js/mixin.js

Small UI improvement in download view, thanks to that, it is visible that something is happening after click (so, you don't have click once again). Especially useful when working with larger datasets.

improvement in responsivness of download view

---

tools/heroku.sh

Fix failure of Heroku deployment (#234).
Test Button for Heroku deploy is following.
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/chakki-works/doccano/tree/issue_234)

Bugfix/Fix failure of Heroku deployment (#234)

---

app/server/static/components/annotationMixin.js
app/server/static/components/document_classification.vue

Small changes to the code replacing some `for` loops.

Remove some for loops

---

app/server/static/components/annotation.pug

Add a page counter at the bottom of the current document:

Add page counter

---

.gitignore
Procfile
app.json
heroku.yml
tools/heroku.sh

Thies PR enables using Dockerfile when deploying Heroku from `app.json` (Heroku Button).
It will solve both #262 and #308.
You can try deploy form this branch by following Heroku Button
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fchakki-works%2Fdoccano%2Ftree%2Fheroku_docker)

Enhancement/Enable Heroku deploy from Dockerfile

---

app/server/static/components/label.vue
app/server/static/package-lock.json
app/server/static/package.json

Addressing chakki-works#175 by adding a dropdown of contrasting default colors. Randomizer button is still available and text box color picker is within the dropdown.

Added color dropdown to help choose contrasting colors for the labels.

---

README.md

This addresses the issues seen during https://github.com/chakki-works/doccano/issues/246

Improve metadata import/export example

---

docs/faq.md
docs/index.md
docs/roadmap.md
mkdocs.yml

I was reading https://chakki-works.github.io/doccano and found a few small issues that I fix in this PR.
To build the docs yourself: 
```bash
pip install mkdocs mkdocs-material
mkdocs serve
```

Cleanup mkdocs website

---

app/requirements.txt
requirements.txt

This change fixes Tornado vulnerabilities.
Fix #447

Bugfix/Fix vulnerabilities in Tornado

---

app/requirements.txt
requirements.txt

Remove unused dependencies

---

frontend/components/organisms/labels/LabelCreationForm.vue

Bugfix: create label over 26

---

frontend/components/containers/annotation/Paginator.vue
frontend/store/pagination.js

Enable to move any page

---

frontend/components/containers/annotation/Paginator.vue
frontend/components/molecules/EntityItem.vue
frontend/components/organisms/annotation/EntityItemBox.vue
frontend/nuxt.config.js
frontend/plugins/vue-shortkey.js

Disable left/right shortcut key in input and textarea

---

app/server/static/package-lock.json
app/server/static/package.json

Update webpack version

---

nginx/nginx.conf

add X-XSS-Protection and X-Content-Type-Options headers

Update nginx.conf to enhance security

---

app/api/urls.py
app/api/views.py
app/app/settings.py
app/app/urls.py
app/requirements.txt
requirements.txt

Add API document generator

---

app/api/tests/data/invalid_labels.json
app/api/tests/data/valid_labels.json
app/api/tests/test_api.py
app/api/urls.py
app/api/views.py
frontend/components/containers/labels/LabelActionMenu.vue
frontend/components/organisms/labels/LabelImportForm.vue
frontend/services/label.service.js
frontend/store/labels.js

[Bugfix] enable to show error messages on importing labels

---

frontend/services/auth.service.js

Fix login/logout problem

---

docker-compose.dev.yml
frontend/components/organisms/layout/TheHeader.vue
frontend/store/auth.js

Fixes https://github.com/doccano/doccano/issues/604
Sample screenshots:
Unlogged in:
For admin:
For non admin:
For signout:
Also updated docker dev script because without debug cors issue was happening.

Username added at the top right corner of doccano

---

frontend/components/containers/annotation/ApproveButton.vue
frontend/layouts/annotation.vue

Fix toolbar vanishment

---

frontend/components/containers/annotation/FilterButton.vue

Fix filter initial state

---

app/api/utils.py

Enable to display non-ascii metadata

---

frontend/store/projects.js

Hey @Hironsan 
This fixes https://github.com/doccano/doccano/issues/593. 
PFB the screenshot:

Clarified input format

---

frontend/layouts/project.vue
frontend/middleware/check-admin.js
frontend/pages/projects/_id/dataset/index.vue
frontend/pages/projects/_id/guideline/index.vue
frontend/pages/projects/_id/index.vue
frontend/pages/projects/_id/labels/index.vue
frontend/pages/projects/_id/members/index.vue
frontend/pages/projects/_id/statistics/index.vue

Remove middleware duplication

---

.travis.yml

Fix mkdocs and mkdocs-material version

---

.gitignore
app/api/views.py

Hey @Hironsan 
This PR fixes https://github.com/doccano/doccano/issues/486.
PFB the earlier snapshots and latest snapshots:
Old: 
New:
Old:
New:

Updated statistics page user data graph

---

app/app/settings.py

Add CORS whitelist

---

frontend/components/organisms/layout/TheHeader.vue
frontend/store/auth.js

Hey @Hironsan 
I have added username in localstorage because otherwise username at the top right of the page used to disappear whenever refresh used to happen. 
This is in continuation with https://github.com/doccano/doccano/issues/604 issue, https://github.com/doccano/doccano/pull/664 pr and https://github.com/doccano/doccano/pull/664#issuecomment-610816764 .
Thanks.

Added username in localstorage

---

docs/faq.md

Add a notification to logout from the Django admin site before login to doccano.

Update FAQ (#723)

---

docs/faq.md

Hey @Hironsan @icoxfog417 
I have updated the faq with information discussed in https://github.com/doccano/doccano/issues/709. 
Thanks.

Updated faq with rebuild info

---

tools/install-mssql.sh

Fixes #773 by allowing downgrades while deploying to heroku

Added flag for allowing downgrades while using apt

---

app/api/tests/test_api.py
app/api/urls.py
app/api/views.py

Anonymous endpoint that may be used by a container platform to verify
availability of the application.
Simply returns: HTTP/200 {"status":"green"}
Future iterations could extend this into reflecting status of
dependencies like database connections.

Extremely simple /v1/health endpoint

---

app/Dockerfile

Tiny fix to make docker a bit lighter.

Dockerfile cleanup

---

app/server/static/assets/css/annotation.css

Display newlines for sequence-labeling projects in old frontend

---

docs/faq.md

FAQ correction

---

app/server/templates/index.html
frontend/components/organisms/layout/TheTopBanner.vue

This PR makes a few grammar improvements that I noticed when looking at the [CoronaWhy instance](http://doccano.coronawhy.org/) of doccano. If you'd like me to do more proofreading, please let me know!

Improve home page text

---

app/app/settings.py
awsdeploy.yml

1. Fix creating admin user #492
2. Add additional variables for deploy:
- SMTP and default email settings. Fix #663
- Workers count
-  Docker image name

Fix aws deploy

---

frontend/components/containers/annotation/BottomNavigator.vue
frontend/components/containers/annotation/Paginator.vue
frontend/components/containers/documents/DocumentList.vue

bug: fix to bug #850. Now is possible to open documents from other pages

---

frontend/components/containers/annotation/FilterButton.vue

Fix choosing filter twice results in 404 error, closes #754

---

frontend/components/organisms/layout/TheSideBar.vue

Highlight current page in the side bar

---

frontend/components/organisms/annotation/MultiClassClassification.vue
tools/install-mssql.sh

Fix 400 error on text classification

---

frontend/components/organisms/layout/TheTopBanner.vue
frontend/pages/auth.vue
frontend/pages/demo/named-entity-recognition/index.vue
frontend/pages/demo/sentiment-analysis/index.vue
frontend/pages/demo/text-to-sql/index.vue
frontend/pages/demo/translation/index.vue
frontend/pages/index.vue

Fix missing icon

---

frontend/components/containers/annotation/TextClassification.vue

Keep the new line in the text classification

---

frontend/components/organisms/layout/TheHeader.vue
frontend/layouts/default.vue
frontend/layouts/demo.vue

Fix the header behavior in the error page

---

frontend/layouts/annotation.vue
frontend/store/projects.js

Hide check button from annotators

---

README.md
template.aws.yaml

Update CloudFormation template

---

tools/install-mssql.sh

Update install-mssql.sh not to specify curl version

---

frontend/components/containers/projects/ProjectDeletionButton.vue
frontend/store/projects.js

Enable project delete button only for project administrators

---

app/tools/run.sh

Update run.sh to fix #1002

---

app/server/static/components/projects.vue

fix #1008 
fix #1009 
fix #1010 
fix #1019

Rollback server/static/components/projects.vue, fix #1008

---

nginx/nginx.conf

Update nginx config to access swagger in production, fix #1038

---

app/server/static/components/annotationMixin.js

Fix approve annotation documents function

---

frontend/components/containers/documents/DocumentList.vue

Fix: AnnotateButton now links to the right docs

---

frontend/components/containers/labels/LabelList.vue

Show only available shortcut keys

---

app/api/views.py

Deduplicate data on randomized order option

---

docker-compose.dev.yml
docker-compose.prod.yml
frontend/nuxt.config.js
frontend/package.json
frontend/yarn.lock

Enable to login on remote machine

---

app/tools/run.sh

Fix backend container fail

---

README.md
app/app/settings.py
app/doccano/doccano.py
setup.py

Fix pg_config error on pip installation

---

app/app/settings.py
setup.py

Fix #1103
Fix #1106 
Fix #1107

Fix Invalid syntax error

---

app/api/tests/data/example_fasttext.txt
app/api/tests/data/example_fasttext_label_tag_without_name.txt
app/api/tests/data/example_fasttext_without_text.txt
app/api/tests/test_api.py
app/api/utils.py
app/api/views.py
frontend/store/projects.js

Functionality to import files in the popular FastText format.

FastText import functionality

---

app/api/tests/test_api.py
app/api/views.py
app/server/static/components/download_sequence_labeling.vue
frontend/components/organisms/documents/DocumentExportForm.vue
frontend/i18n/en/projects/dataset.js
frontend/store/documents.js
frontend/store/projects.js

Enhancement/dynamic filename + changed json1 naming to jsonl

---

.github/workflows/ci.yml
Pipfile
Pipfile.lock

This is the first step to transfer Travis to GitHub Actions.

Add GitHub actions for unit testing

---

.github/workflows/publish-image.yml
Dockerfile

Proper tagging of docker containers

---

app/requirements.txt

Quick fix #1130

---

app/api/views.py
frontend/components/organisms/documents/DocumentExportForm.vue
frontend/services/document.service.js
frontend/store/documents.js

Enhancement: Added option to export only approved datasets

---

app/api/models.py
app/api/serializers.py
app/api/tests/test_models.py

Now we can turn on `Debug=True`.
fix #713

Fix 500 error after project creation

---

Dockerfile
app.json
tools/heroku.sh

Fix heroku deploy

---

app/api/tests/test_api.py
app/api/utils.py
app/api/views.py
frontend/services/document.service.js
frontend/store/projects.js

Functionality to export documents in the fastText format.

Feature: FastText Export (#362)

---

frontend/components/organisms/documents/DocumentUploadForm.vue
frontend/i18n/en/projects/dataset.js
frontend/i18n/en/projects/errors.js
frontend/rules/index.js

Feature: bulkimport for same filetype.

---

frontend/i18n/en/rules.js
frontend/rules/index.js
nginx/nginx.conf

This is in response to  https://github.com/doccano/doccano/issues/706 which was closed for an unclear reason 
Feel free to reject the PR if it triggers some issue I  am not aware of.
Tested using docker-compose.prod.yml and docker-compose.dev.yml  with a  3MB dataset. If you want more testing before merging, then please tell me the filesize needed.

Increased max upload size to  100 MB.

---

frontend/components/organisms/annotation/EntityItemBox.vue

Fix a method counts the number of characters

---

docs/project_structure.md

fix doc bug

---

frontend/components/organisms/layout/TheSideBar.vue
frontend/i18n/en/index.js
frontend/i18n/en/projects/settings.js
frontend/pages/projects/_id/settings/index.vue

Add project edit page

---

frontend/components/organisms/labels/LabelImportForm.vue
frontend/rules/index.js

Add a single file rules

---

app/Dockerfile.dev
app/Dockerfile.prod

Update libpq-dev version to avoid build failure

---

setup.py

Add auto-labeling-pipeline to a dependency in setup.py

---

frontend/package.json
frontend/pages/projects/_id/guideline/index.vue
frontend/yarn.lock

Remove vuex from the guideline page.

[Enhancement] guideline

---

frontend/models/statistics.ts
frontend/pages/projects/_id/statistics/index.vue
frontend/plugins/services.ts
frontend/repositories/statistics/api.ts
frontend/repositories/statistics/interface.ts
frontend/services/application/statistics.service.ts

Remove vuex from the stats page.

[Enhancement] statistics

---

frontend/components/label/FormCreate.vue
frontend/i18n/de/rules.js
frontend/i18n/en/rules.js
frontend/i18n/fr/rules.js
frontend/i18n/zh/rules.js

Change the limit length of label name from 30 to 100 characters

---

frontend/pages/projects/_id/text-classification/index.vue

Add v-shortkey to text classification page

---

app/api/tests/test_api.py
app/api/views/annotation.py
frontend/components/project/FormCreate.vue
frontend/components/tasks/textClassification/SingleLabel.vue
frontend/domain/models/project/project.ts
frontend/pages/projects/_id/text-classification/index.vue
frontend/pages/projects/index.vue
frontend/services/application/project/projectApplicationService.ts
frontend/services/application/project/projectData.ts

[Enhancement] single label

---

setup.py

Add dj-rest-auth to setup.py

---

frontend/components/label/LabelList.vue
frontend/components/member/MemberList.vue
frontend/components/project/ProjectList.vue

Fix rows per page error

---

frontend/pages/projects/_id/sequence-to-sequence/index.vue
frontend/pages/projects/_id/text-classification/index.vue

Add pre-wrap class to classification page

---

backend/app/settings.py

Replace postgres url for heroku

---

backend/.dockerignore
backend/Dockerfile.prod
docker-compose.prod.yml
nginx/Dockerfile
nginx/default.conf
nginx/nginx.conf
tools/offline_deployment/offline_01_1-optional_use_https.sh
tools/prod-django.sh

- Use unprivileged user
- Enable a user to access the uploaded files
Confirmed the following environments:
Environment 1:
- Ubuntu 20.04.2 LTS
- Docker version 20.10.5
- docker-compose version 1.28.5
Environment 2:
- macOS Mojave 10.14.1
- Docker version 20.10.5
- docker-compose version 1.29.0

Fix docker-compose.prod.yml

---

backend/Dockerfile.prod

Fix permission for /backend
Issue: #1381

Fix permission for /backend

---

template.aws.yaml

Remove t2.micro from cloudformation template

---

backend/api/exceptions.py
backend/api/views/auto_labeling.py

Fix `AutoLabeliingPermissionDenied` to `AutoLabelingPermissionDenied`

Fix typo of exception name

---

docker-compose.dev.yml
docker-compose.prod.yml

Specify image names in compose files

---

backend/api/tests/download/test_writer.py
backend/api/views/download/writer.py

Sort exported labels

---

README.md

Added a way to use PostgreSQL when installed with pip.

Add how to use PostgreSQL

---

frontend/components/tasks/sequenceLabeling/EntityEditor.vue
frontend/yarn.lock

Related to #1569 
Related to #1571

[Enhancement] Add an autocomplete in annotation menu

---

Dockerfile

Update Dockerfile to change the default value of DEBUG

---

frontend/components/example/FormDelete.vue
frontend/i18n/en/projects/dataset.js

Show number of deleting rows only in confirm dialog

---

backend/api/views/statistics.py

The current code is very slow for a large dataset.
This PR improves the speed of the statistics API.

Speed up statistics API

---

backend/api/tests/api/test_comment.py
backend/api/urls.py
backend/api/views/comment.py
frontend/components/tasks/toolbar/ToolbarLaptop.vue
frontend/components/tasks/toolbar/forms/FormComment.vue
frontend/domain/models/comment/commentRepository.ts
frontend/repositories/comment/apiCommentRepository.ts
frontend/services/application/comment/commentApplicationService.ts

Move the feature to `CommentProjectList` API and rename it to `CommentList`.

[Enhancement] Remove unnecessary CommentListDoc API

---

backend/members/models.py
backend/members/tests.py

Update clean method in Member

---

backend/api/permissions.py
backend/api/views/project.py

Due to the duplication of IsAdminUser

Remove IsStaff permission

---

Dockerfile
backend/app/urls.py
backend/cli.py
backend/data_import/pipeline/builders.py
setup.py

Enable to show images and audios in the case of pip and Docker

---

backend/api/tests/api/test_project.py
backend/api/views/project.py
frontend/components/project/ProjectList.vue
frontend/domain/models/project/project.ts
frontend/domain/models/project/projectRepository.ts
frontend/pages/projects/index.vue
frontend/repositories/project/apiProjectRepository.ts
frontend/services/application/project/projectApplicationService.ts
frontend/services/application/project/projectData.ts

Enable to paginate projects

---

backend/api/migrations/0033_auto_20220127_0654.py

Fix a migration

---

frontend/components/tasks/sequenceLabeling/EntityEditor.vue
frontend/pages/projects/_id/sequence-labeling/index.vue

Enable to annotate text in a row:
If no label type is selected, the popup is shown:

[Enhancement] Add new labeling option for sequence labeling

---

backend/metrics/views.py
frontend/components/tasks/sidebar/AnnotationProgress.vue
frontend/composables/useExampleItem.ts
frontend/domain/models/metrics/metrics.ts
frontend/domain/models/metrics/metricsRepository.ts
frontend/pages/projects/_id/image-classification/index.vue
frontend/pages/projects/_id/intent-detection-and-slot-filling/index.vue
frontend/pages/projects/_id/sequence-labeling/index.vue
frontend/pages/projects/_id/sequence-to-sequence/index.vue
frontend/pages/projects/_id/speech-to-text/index.vue
frontend/pages/projects/_id/text-classification/index.vue
frontend/repositories/metrics/apiMetricsRepository.ts
frontend/services/application/metrics/metricsApplicationService.ts

[Enhancement] Show progress

---

backend/cli.py

Updates database schema:
```bash
doccano migrate
```

Add migrate command to cli

---

frontend/package.json
frontend/yarn.lock

By using `resolutions` in `package.json`, upgrade some sub-packages.

Upgrade npm packages

---

frontend/components/example/AudioList.vue
frontend/components/example/DocumentList.vue
frontend/components/example/ImageList.vue

Show id in database page

---

backend/cli.py

```bash
doccano webserver --workers=4
```
resolve #1598

Support workers option, 

---

frontend/package.json
frontend/yarn.lock

Reference:
- https://github.com/substack/minimist/issues/164

Update minimist version

---

backend/examples/serializers.py

This pull request tries to solve issue #1765.
It is a small change and in my tests it seems to work but i would like to test it on the whole test pipeline, so i'm submitting a draft pull request.
If you have any advice i'm here to follow yours.

add confirmed_at field to ExampleStateSerializer

---

backend/data_export/celery_tasks.py
backend/data_export/pipeline/factories.py
backend/data_export/pipeline/repositories.py
backend/data_export/tests/test_repositories.py

fix empty export in entity-relationship-labeling

---

docker/Dockerfile.prod
docker/docker-compose.prod.yml

Add tmp_file as a volume

---

backend/data_export/pipeline/repositories.py
backend/data_export/tests/test_repositories.py

Fix #1392 
Fix #1416 
Fix #1422

Fix dataset export problem

---

.github/workflows/ci.yml
frontend/.eslintrc.js
frontend/components/auth/FormLogin.vue
frontend/composables/useLabelList.ts
frontend/composables/useProjectItem.ts
frontend/middleware/check-admin.js
frontend/nuxt.config.js
frontend/pages/projects/_id/dataset/import.vue
frontend/plugins/services.ts
frontend/repositories/comment/apiCommentRepository.ts
frontend/repositories/project/apiProjectRepository.ts
frontend/repositories/tasks/sequenceLabeling/apiRelationRepository.ts
frontend/services/application/autoLabeling/configApplicationService.ts
frontend/services/application/label/labelApplicationService.ts
frontend/services/application/tag/tagApplicationService.ts
frontend/test/unit/components/tasks/toolbar/forms/formGuideline.spec.js

Add frontend lint to the workflow

[Enhancement] frontend linter

---

backend/data_export/pipeline/catalog.py
backend/data_export/views.py

Enable to show relation export format in frontend

Fix relation export

---

frontend/components/tasks/toolbar/ToolbarLaptop.vue

Fix the position of the toolbar

---

backend/data_import/datasets.py
backend/data_import/pipeline/examples.py
backend/data_import/pipeline/labels.py
backend/data_import/tests/test_examples.py
backend/data_import/tests/test_labels.py

- Add Examples class
- Reduce the number of queries(related to Example)

[Enhancement] refactor data import

---

docker/docker-compose.prod.yml

update docker-compose: set nginx image name to doccano_nginx:prod

update docker-compose: set nginx image name to doccano_nginx:prod

---

backend/config/settings/heroku.py

fix #1905
fix #1814 
fix #1778

Enable to access to admin site on Heroku

---

frontend/package.json
frontend/yarn.lock

Upgrade v-annotator

---

docs/mkdocs.yml

Update mkdocs config

---

frontend/components/layout/TheHeader.vue
frontend/components/project/FormCreate.vue
frontend/i18n/en/home.js
frontend/i18n/en/projects/overview.js
frontend/i18n/fr/home.js
frontend/i18n/fr/projects/comments.js
frontend/i18n/fr/projects/links.js
frontend/i18n/fr/projects/settings.js

* add new french translations
* add variables to translate to french
* do the necessary treatment for english

lang: add new french translation and new variables

---

frontend/components/layout/LocaleMenu.vue
frontend/components/layout/TheHeader.vue

Set z-index to the header

---

frontend/components/example/AudioList.vue
frontend/components/example/DocumentList.vue
frontend/components/example/ImageList.vue

Show status on dataset page

---

cloud/aws/template.aws.yaml

Remove t2.small option due to OOM

---

backend/cli.py
backend/poetry.lock
backend/pyproject.toml
docker/.env.example
docker/docker-compose.prod.yml
docs/developer_guide.md
docs/install_and_upgrade_doccano.md
tools/prod-flower.sh
tools/run.sh

Add [Flower](https://flower.readthedocs.io/en/latest/index.html) to the following environment:
- Pip
- Docker
- Docker Compose

[Enhancement] Add Flower to monitor and manage Celery tasks

---

backend/data_export/celery_tasks.py
backend/data_import/celery_tasks.py

- import_dataset
- export_dataset

Add retry setting explicitly to celery tasks

---

docker/Dockerfile
docker/Dockerfile.prod

Update poetry version to v1.2.0

---

.github/workflows/test-installation.yml

- Test pip installation
- Test `doccano init` command
- Test `doccano createuser` command

Add workflow to test installation and commands

---

backend/api/management/commands/create_admin.py
backend/api/tests/test_commands.py

Warn if default password is not changed

---

.github/workflows/publish-image.yml

- Stop outputting Git short commit
- Stop building on pushing master branch

Update publish-image workflow

---

docker/Dockerfile.prod

Update `Dockerfile.prod` to reduce the image size.

Reduce the image size(doccano:backend)

---

.github/workflows/publish-image.yml

Platforms:
- linux/amd64
- linux/arm64

Specify platform on publish-image workflow

---

backend/auto_labeling/tests/test_views.py

Add a test case of auto labeling for nonexistent category

---

docs/CONTRIBUTING.md

Describe development workflow
resolve #1928

Improve contribution guide

---

backend/cli.py
backend/config/settings/production.py
tools/prod-django.sh
tools/run.sh

Add logging to production.py to reduce the time of troubleshooting.

[Enhancement] setting logging

---

docker/Dockerfile
docker/Dockerfile.nginx

When building the docker images on CI, the following message is repeatedly displayed.
```bash
info There appears to be trouble with your network connection. Retrying...
```
This PR try to solve the problem.

Update yarn install line

---

backend/poetry.lock
backend/pyproject.toml

- joblib
- protobuf
- django-storages
- google-cloud-storage

Update python packages

---

frontend/pages/projects/_id/intent-detection-and-slot-filling/index.vue

Make auto labeling working in intent detection

---

frontend/pages/projects/_id/sequence-labeling/index.vue

Enable to expand/collapse label types card

---

frontend/pages/projects/_id/image-captioning/index.vue
frontend/pages/projects/_id/image-classification/index.vue
frontend/pages/projects/_id/intent-detection-and-slot-filling/index.vue
frontend/pages/projects/_id/object-detection/index.vue
frontend/pages/projects/_id/segmentation/index.vue
frontend/pages/projects/_id/sequence-labeling/index.vue
frontend/pages/projects/_id/sequence-to-sequence/index.vue
frontend/pages/projects/_id/speech-to-text/index.vue
frontend/pages/projects/_id/text-classification/index.vue

Trigger auto labeling automatically

---

backend/poetry.lock
backend/pyproject.toml

Fix installation issue

---

backend/config/settings/base.py
backend/config/settings/development.py
docs/faq.md

Fix #1820 
Fix #1918 
Fix #2032 
Fix #2062
Fix #2067

Enable to set CSRF_TRUSTED_ORIGINS in debug mode

---

frontend/pages/projects/_id/intent-detection-and-slot-filling/index.vue

Enable to use shortcut keys for classification

---

docs/faq.md
frontend/components/example/AudioList.vue
frontend/components/example/ImageList.vue
frontend/domain/models/example/example.ts
frontend/nuxt.config.js
frontend/pages/projects/_id/image-captioning/index.vue
frontend/pages/projects/_id/image-classification/index.vue
frontend/pages/projects/_id/object-detection/index.vue
frontend/pages/projects/_id/segmentation/index.vue
frontend/pages/projects/_id/speech-to-text/index.vue

Enable to show images after changing port number (docker-compose)

---

backend/data_import/pipeline/label.py
backend/data_import/pipeline/labels.py
backend/data_import/tests/test_label.py
backend/data_import/tests/test_labels.py

Update the way to import relational dataset

---

app.json

Update postgres addon in app.json

---

backend/config/settings/base.py

Fix "Site matching query does not exist." error

Add SITE_ID to base.py

---

frontend/components/comment/CommentList.vue

This is a feature proposed in #1883 . It's a simple change but in my case it's really useful and helps with collaboration.

Add example number to comment list.

---

frontend/components/example/DocumentList.vue
frontend/pages/projects/_id/dataset/_example_id/edit.vue
frontend/pages/projects/_id/dataset/index.vue

[Feature] Enable to edit text

---

frontend/domain/models/project/project.ts
frontend/pages/projects/_id/dataset/index.vue

- isImageProject
- isAudioProject

Add fields to project model

---

frontend/yarn.lock

Upgrade nuxt version

---

backend/examples/views/comment.py
frontend/components/comment/CommentList.vue
frontend/repositories/comment/apiCommentRepository.ts

Enable to sort comments by example

---

backend/projects/models.py
backend/projects/tests/test_project.py
backend/projects/urls.py
backend/projects/views/project.py
frontend/pages/projects/index.vue
frontend/repositories/project/apiProjectRepository.ts
frontend/services/application/project/projectApplicationService.ts

Enable to clone the following data:
- project
- dataset (examples)
- label types
Resolve #1818

[Enhancement] Support clone project

---

frontend/middleware/setCurrentProject.ts
frontend/pages/projects/_id/comments/index.vue
frontend/pages/projects/_id/dataset/_example_id/edit.vue
frontend/pages/projects/_id/dataset/index.vue
frontend/pages/projects/_id/labels/_label_id/edit.vue
frontend/pages/projects/_id/labels/add.vue
frontend/pages/projects/_id/labels/import.vue
frontend/pages/projects/_id/labels/index.vue
frontend/pages/projects/_id/metrics/index.vue

Projects were sometimes fetched more than once. So this PR fixes the problem.

Remove fetching projects more than once

---

README.md
docs/developer_guide.md
docs/faq.md
docs/index.md
docs/mkdocs.yml
docs/tutorial.md

Edit doccano docs for grammar, clarity, and concision.
- Add context around admin login and changing passwords
- Incorporate ordered steps in FAQ and tutorial
- Update get started links
- Streamline language and formatting
Resolves https://github.com/doccano/doccano/issues/2215

Edit doccano docs

---

backend/examples/filters.py
backend/examples/tests/test_filters.py
frontend/components/example/AudioList.vue
frontend/components/example/DocumentList.vue
frontend/components/example/ImageList.vue
frontend/repositories/example/apiDocumentRepository.ts

[Enhancement] Support dataset filtering by label name

---

docker/Dockerfile.nginx

Update node image version

---

backend/examples/filters.py
frontend/repositories/example/apiDocumentRepository.ts

This PR enables filtering the examples within a project by assignee:
Regards

feature: filter examples by assignee
