doccano/doccano

app/server/templates/annotation/annotation_base.html

After changing the paths loading the two js modules, annotation works well.
Fix #48 #49

Fixes #49 and #48

---

.dockerignore
.gitignore
.travis.yml
Dockerfile
app/app/settings.py
tools/ci.sh
tools/run.sh

As per https://github.com/chakki-works/doccano/projects/2#card-16406087, this change adds a Dockerfile for the project.
The Python distribution used by the image can be specified via a build-time argument. This enables us in the future to for example run the tests on a wide variety of Python versions.
In the future, the Dockerfile could be extended to for example leverage multi-stage builds. In this case, the first stage could run tests, linter, and so forth and then create a wheel or similar artifact via setuptools. A second stage in the build can then only include a minimal set of dependencies to install and run the artifact (e.g. using python-slim as a base image).

Feature/Add Dockerfile

---

app/app/settings.py
app/app/urls.py
app/server/templates/base.html
app/server/templates/login.html
app/server/views.py
requirements.txt

Currently the workflow for adding new users to a doccano instance requires an administrator to create accounts using the Django admin tool. This puts a burden on the admin. It also puts a burden on the user since they must maintain a dedicated account and password to access this application. See also the discussion on [card-16405801](https://github.com/chakki-works/doccano/projects/2#card-16405801) around user management.
To make it easier for annotators to do work on doccano, I suggest to add social authentication to the application. This means that a user can sign up with the social provider and get invited to work on annotation projects using that social identity.
As a first step, this pull request implements Github and Azure Active Directory authentication but other social identities …

Feature/Add social login via Github and Active Directory

---

README.md
app/server/management/commands/create_admin.py
app/server/management/commands/wait_for_db.py
azuredeploy.json
tools/create-admin.sh
tools/run.sh

Currently the application can easily be deployed to Heroku via the Procfile. This change adds an [ARM template](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview) to additionally easily deploy the application to Azure.
To make management of the application as straight forward as possible, the ARM template leverages PaaS solutions: the Django application is deployed via the Docker container to a [Web App for Containers](https://azure.microsoft.com/en-us/services/app-service/containers/) and the app's data storage is a [managed PostgreSQL](https://azure.microsoft.com/en-us/services/postgresql/) instance.
For additional security, the PostgreSQL database is configured to only allow connections from other Azure IPs. If someone wishes to connect to the …

Feature/Add Azure deployment automation

---

.travis.yml
tools/cd.sh

This change adds continuous delivery of the doccano Docker image to DockerHub. Whenever a tag is created in the repository (e.g. via authoring a release on Github), Travis will build the project and push the image to Docker. The `latest` Docker tag will be updated to the current release and a new Docker tag will be created which is named the same as the git tag.
Example successful release build: [logs](https://travis-ci.org/CatalystCode/doccano/builds/485408772), [images](https://cloud.docker.com/repository/registry-1.docker.io/cwolff/doccano/tags).
Open questions:
- Do you have a Docker account which you'd like to use for the images?
- If yes: could you please add `DOCKER_USERNAME` and `DOCKER_PASSWORD` in the Travis settings page for doccano …

Feature/Add continuous delivery of images to DockerHub

---

requirements.txt

As of the title, it was fixed warning of psycopg2.
According to the message that psycopg 2 is renamed to psycopg 2 - binary as the version is upgraded.
```
$ docker exec doccano tools/create-admin.sh "admin" "admin@example.com" "password"
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary
please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
""")
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary
please use "pip install psycopg2-binary" instead. For …
```

Fix psycopg2 warning by updating to psycopg2-binary

---

Procfile
README.md
app.json
package.json
tools/heroku.sh

This pull request implements [Heroku Button](https://devcenter.heroku.com/articles/heroku-button) to enable one-click deployment on the Heroku.
* Heroku Button on the `README.md` is enabled after the merge. Because Heroku Button refers `master` branch by default.
* The following button is specified to use my branch ([`icoxfog417/doccano/tree/heroku_button`](https://github.com/icoxfog417/doccano/tree/heroku_button)). You can use it to test/confirm the behavior.
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/icoxfog417/doccano/tree/heroku_button)
I already confirm the demo app & annotation on the created project works fine.

Implement Heroku Button

---

README.md
app/server/static/js/sequence_labeling.js

This PR makes doccano support for emoji annotation. The problem is described in #99.
Due to the encoding used by javascript, the emoji length is different between python and javascript.
```
{"text": "label1 😄 label2, label3"}
{"text": "label1 🎊 label2, label3"}
{"text": "label1 👩‍❤️‍👩 label2, label3"}
```
**before**
emoji_export.json
```
{"doc_id": 3, "text": "label1 😄 label2, label3", "entities": [[7, 9, "l1"], [10, 16, "l2"]], "username": "admin", "metadata": {}}
{"doc_id": 4, "text": "label1 🎊 label2, label3", "entities": [[7, 9, "l1"], [10, 16, "l2"]], "username": "admin", "metadata": {}}
{"doc_id": 5, "text": "label1 👩‍❤️‍👩 label2, label3", "entities": [[7, 15, "l1"], [16, 22, "l2"]], "username": "admin", "metadata": {}}
```
**after**
emoji_export.json
```
{"doc_id": 42, "text": …
```

Correct emoji length calculation

---

README.md

Recently when building Doccano, I had to change a few configurations in order to setup `npm` and `node.js` properly.  Given the following lines of the installation instructions...
```bash
cd server
npm install
npm run build
cd ..
```
...adding `Node.js 8.0+` as a requirement made sense to me.

add nodejs requirement to readme

---

README.md
awsdeploy.yml

This pull request implements AWS launch button to deploy doccano on AWS quickly.
[![AWS CloudFormation Launch Stack SVG Button](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?templateURL=https://s3-external-1.amazonaws.com/cf-templates-10vry9l3mp71r-us-east-1/20190732wl-new.templatexloywxxyimi&stackName=doccano)
* Launch Button on the `README.md` and description.
* `awsdeploy.yml` is the AWS Cloudformation template
TODO

#87: implement AWS launch button

---

.dockerignore
.gitignore
README.md
app/app/settings.py
app/server/package-lock.json
app/server/package.json
app/server/templates/admin/dataset.html
app/server/templates/admin/download/base.html
app/server/templates/admin/guideline.html
app/server/templates/admin/label.html
app/server/templates/admin/stats.html
app/server/templates/admin/upload/base.html
app/server/templates/annotation/document_classification.html
app/server/templates/annotation/seq2seq.html
app/server/templates/annotation/sequence_labeling.html
app/server/templates/demo/demo_named_entity.html
app/server/templates/demo/demo_text_classification.html
app/server/templates/demo/demo_translation.html
app/server/templates/projects.html
app/server/webpack.config.js
requirements.txt

This is a follow-up to https://github.com/chakki-works/doccano/pull/80.
This pull request more tightly integrates Django asset serving with the Webpack compiler. Specifically, after this change, it will no longer be required to manually compile the project's Javascript to integrate it with the Django server. Instead the Javascript will be compiled and reloaded on the fly automatically.
In a development scenario (here emulated by running the server as described in the README), the assets get linked via the hot reloading Webpack development server:
This enables a number of enhancements to the developer experience, including not having to manually run the Webpack build and also being able to debug Javascript before it went through the build process:
In a production scenario (here emulated by …

Enhancement/Integrate Webpack and Django

---

Dockerfile

Using a multi-stage build reduces the image size from 1.23GB to 331MB which means that any node running doccano can now start-up faster.
Additionally, the multi-stage build means that we no longer include in the production image development tools like node (now excluded since it's only installed in the builder layer) or gcc (now excluded since the production layer is based on python-slim) which reduces the attack surface of the image.

Enhancement/Turn dockerfile into a multi-stage build

---

app/server/utils.py

Fix for 
```
Internal Server Error: /v1/projects/2/docs/upload
Traceback (most recent call last):
File "/doccano/app/server/utils.py", line 347, in parse
raise StopIteration
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/doccano/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/doccano/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/doccano/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File …
```

Fix issue with text import yielding internal server error

---

app/server/package-lock.json
app/server/package.json
app/server/static/js/demo/demo_mixin.js
app/server/static/js/guideline.js
app/server/static/js/mixin.js
app/server/templates/admin/guideline.html
app/server/templates/annotation/annotation_base.html

Previously some of the Vue code relied on script tags being present in the host application, to include dependencies such as lodash or marked. This is not ideal for encapsulation since it means the Vue components are not self-contained, makes testing harder, etc.
As such, this change replaces the script tag includes with ES6 imports.
Additionally, the lodash dependency (which was used only for debouncing) is replaced in this change with the vue-debounce library which offers a debouncing directive. This simplifies the code and avoids potential gotchas with the this context in the debounced function.

Enhancement/Move from script tags to Javascript imports

---

app/server/templates/base.html
app/server/templates/index.html

Currently the Swiper library is referenced in the base template which means that its CSS and JS get included and loaded on every page. However, the Swiper functionality is only used on the landing page. This leads to redundant requests to load the CSS and JS and may even lead to hard to debug potential issues with clashing JS or CSS.
This change moves the Swiper JS and CSS to only be included on the landing page.

Enhancement/Reduce scope of Swiper include

---

app/server/api.py
app/server/api_urls.py
app/server/serializers.py

Currently, when checking whether the user is a superuser or not, or showing the username, it depends on the Django context.
This PR adds `me API`, which returns the user information. For using this API, we will be able to reduce the dependency.
Me API can return information like follows:
```
{
"id": 1,
"username": "hironsan",
"first_name": "",
"last_name": "",
"email": "",
"is_superuser": true
}
```

Feature: Implement me API

---

app/server/templates/annotation/annotation_base.html

Currently if a superuser accesses any of the demo pages, the Django server crashes with a NoReverseMatch as shown in the screenshot below:
This is caused by the fact that the demo pages re-use the annotation base template. When the user is a superuser, the annotation base template includes a link to edit the current project id. However, demo
projects don't have an id which causes the crash. This change fixes the crash by only including the project edit link if the Django context contains a project id.

Bugfix/Fix NoReverseMatch on demo page for superuser

---

app/app/settings.py
requirements.txt

Currently, whenever the database is changed from the default SQLite via the DATABASE_URL environment variable, the connection to the database is forced to be SSL. This is a great default for production use-cases. However, in some scenarios, users may not want to use SSL, e.g. when testing against a local MySQL or PostgreSQL database.
This change enables users to explicitly request a non-SSL connection to the database by passing the `?sslmode=disable` (or similar) query argument in the DATABASE_URL environment variable.
For backwards compatibility, if the `sslmode` is not set explicitly in the connection URL, the code still defaults to requiring SSL on the connection.

Enhancement/Enable non-SSL connections to the database

---

Dockerfile
app/app/settings.py
app/server/tests/test_config.py

There is an issue in [dj-database-url](https://pypi.org/project/dj-database-url/) which [always sets the sslmode even if the underlying engine doesn't support SSL](https://github.com/kennethreitz/dj-database-url/blob/v0.5.0/dj_database_url.py#L127-L128). See also the [conversation](https://github.com/chakki-works/doccano/pull/170#issuecomment-490023067) with @deltatree on https://github.com/chakki-works/doccano/pull/170 for more information.
There also is an issue in [django-heroku](https://pypi.org/project/django-heroku/) which seems to always override sslmode=True. See also the [conversation](https://github.com/chakki-works/doccano/pull/170#issuecomment-490543552) with @dveselov on https://github.com/chakki-works/doccano/pull/170 for more information.
This change implements a …

Bugfix/Fix sslmode with custom sqlite path and on Heroku

---

.travis.yml
tools/cd.sh

As discussed in https://github.com/chakki-works/doccano/issues/182, this change publishes a new docker image on each master build which enables users to more quickly get access to new versions of doccano.
The master builds are named like `travis-[0-9]+` to differentiate them clearly from official manual releases via git tags which preserve the exact name of the tag as the docker image name (just like prior to this change). Additionally, the `latest` docker image gets updated on each build.
The screenshot below shows an example of a master docker image and a release docker image published by the new CD script:

Enhancement/Publish each master to Docker Hub

---

app/server/tests/test_config.py
azuredeploy.json

In the Azure deploy the database user is in the format `user@server` and it looks like furl doesn't deal well with that. URL-encoding the `@` to `%40` fixes the problem.
Resolves https://github.com/chakki-works/doccano/issues/203

Bugfix/Encode username in Azure DATABASE_URL

---

README.md
app/server/webpack.config.js
docker-compose.yml
tools/dev-django.sh
tools/dev-webpack.sh

This pull request adds a compose file to set up the development environment with just one command: `docker-compose up`.
The compose file runs and links the Django server, Webpack devserver and a Postgres database. An admin user is also created if it doesn't exist yet.
The compose file uses standard base images (`node:8` and `python:3.6`) and injects the code via bind-mounts. This approach provides an efficient development experience by avoiding the Docker build step and also enabling automatic reloading of the Django and Webpack servers when the code is changed.
To prevent potential issues resulting from differences in the operating system in the containers and the host operating system, the virtualenv and node_modules are hidden from the host via volumes.

Enhancement/Add Docker-Compose file for development

---

.gitignore
app/app/settings.py
azure-pipelines.yaml
azuredeploy.json
requirements.txt
tools/azure.sh
tools/cd.sh

This pull request adds support for Azure Pipelines as a CI provider to offer users an alternative option to Travis. Azure Pipelines has a [free tier for open source projects](https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/) and a bunch of nice features like [nice test result visualization](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops).
The Azure Pipelines definition also includes optional CD which publishes new master builds to a container registry and then deploys the images to a live system via the existing Azure deployment template. This will be useful to ensure that users can always easily upgrade to running the latest version of the code in …

Enhancement/Integrate with Azure Pipelines

---

app/app/settings.py
app/server/social_auth.py
app/server/tests/cassettes/TestAzureADTenantSocialAuth.test_fetch_permissions_is_admin.yaml
app/server/tests/cassettes/TestAzureADTenantSocialAuth.test_fetch_permissions_not_admin.yaml
app/server/tests/cassettes/TestGithubSocialAuth.test_fetch_permissions_is_admin.yaml
app/server/tests/cassettes/TestGithubSocialAuth.test_fetch_permissions_not_admin.yaml
app/server/tests/test_social_auth.py
requirements.txt

In https://github.com/chakki-works/doccano/pull/75, the option to log into doccano via third-party auth providers was added. This pull request extends the previous work and enables the management of user admin status in the third-party auth providers. Specifically:
- If a user logs in via Github and is member of a specific organization and specific team, the user will be granted admin status in doccano.
- If a user logs in via Azure Active Directory and is member of a specific group, the user will be granted admin status in doccano.

Enhancement/Read admin info from third-party auth

---

app/server/api.py
app/server/filters.py
app/server/tests/test_api.py

We're using Doccano to collect annotations from multiple people per document. We've found it confusing that the progress bar and document filter on the annotation page includes annotations for **all** users instead of just the current user.
This PR makes two key changes:
1. it updates the progress API end point to only count annotations for the logged in user
2. It updates the document filter to count annotations for the logged in user

Feature/Filter the progress bar & document list by a user's own annotations

---

app/server/admin.py

We **add some columns to the admin page** in order to have a better overview of the table's elements. Nothing big, just a first simple pull request.
- This way, we can see some important features while browsing the admin.
- We also see the element sorted out
- We give the opportunity to search through the elements

we add some columns to the admin page

---

app/server/static/components/annotator.vue
app/server/templates/base.html

This would help to distinguish annotations when there are too many labels to distinguish the colours. Related to the issue https://github.com/chakki-works/doccano/issues/253

Add a tooltip under each annotation to name them

---

app/api/views.py

Currently there are several list APIs that define both `queryset` and `get_queryset` which can be confusing to new developers. This pull request cleans up the list APIs such that only one of `queryset` or `get_queryset` always is used.

Enhancement/Simplify queryset handling in list APIs

---

Dockerfile

Recently the base Python image was updated from Debian stretch to Debian buster. This breaks the CI since the node setup script fails to install npm on buster (sample broke build [1](https://travis-ci.org/CatalystCode/doccano/builds/559133008), [2](https://travis-ci.org/CatalystCode/doccano/builds/559109537)). Pinning the Python image to stretch fixes the issues and should prevent these sorts of regressions in the future (sample passed build [3](https://travis-ci.org/CatalystCode/doccano/builds/559165131)).

Bugfix/Pin Python base image to Debian stretch

---

app/server/static/components/annotator.vue
app/server/static/components/sequence_labeling.vue

Add a yellow highlight to show where the search results are in the text.
One disadvantage of this implementation is that it adds `span`s to the text, but I did not find how to do otherwise.

Add highlight of the search results

---

.travis.yml
Dockerfile
tools/install-mssql.sh

This pull request ensures that Doccano's support for SQL Server (introduced in https://github.com/chakki-works/doccano/pull/255) is covered in the database backend test infrastructure (introduced in in https://github.com/chakki-works/doccano/pull/278).
Given that the database backend tests run in the builder stage of the Dockerfile, this pull request also moves the SQL server system dependency setup into a script so that the code to install the dependencies doesn't have to be copy/pasted between the runtime and builder stages.

Enhancement/Extend integration tests to cover SQL Server database

---

app/authentification/tests/test_template.py

We fix the test for the authentification: 
We reuse the **setenv** function defined in the API package in order to set the proper environment variable for the test

Fix for the authentification test

---

app/api/urls.py
app/app/settings.py

As discussed in https://github.com/chakki-works/doccano/issues/299, there is desire to interact with Doccano via the API since this enables integrating Doccano with others systems, e.g. fetch data from system A, push it into Doccano, and later sync the labels to system B.
In order to facilitate usage of Doccano via the API, this pull request adds token authentication to the API:
```sh
curl 'http://localhost:8000/v1/auth-token' -d '{"username": "user", "password": "pass"}' -H 'Content-Type: application/json'
curl 'http://localhost:8000/v1/me' -H 'Authorization: Token xxxxxxxxx'
```

Enhancement/Enable token authorization for API calls

---

app/server/static/components/preview.vue

The preview Vue component contains logic to determine a file's type given an access URL. This pull request fixes that logic for the case where a URL contains a querystring such as `http://some/file.pdf?q=1`.

Bugfix/Fix filename determination with URL querystring

---

tools/dev-django.sh

Fixes #391 
pyodbc [requires g++ and unixodbc-dev](https://github.com/mkleehammer/pyodbc/wiki/Install#debian-stretch).

Fix docker-compose issue with pyodbc

---

README.md
awsdeploy.yml

Changes:
Ami Id:
I made an issue a few weeks ago about the hard coded AMI id.
https://github.com/chakki-works/doccano/issues/397
The documentation was updated but the AMI is still hard coded.
This solution will dynmically pull the correct ubuntu 16 ami id no matter what region you are in.
Docker ports:
Not sure if I am missing something here, but the app serves on port 8000, but the user data in the cfn template maps 80 to 80. So I changed it to map 80 to 8000. It works when I launch it in my AWS account.
Instance type:
The cfn template asks the user to select an instance type. But then it used a hard coded one anyways. So I changed it to use the selected instance type. I assume this was the intended behavior? I also added t3 instance types. Depending on the region you are in, different …

ami id, docker ports, instance type

---

app/app/settings.py

Many of doccano's settings are currently configurable via the environment as per the [12-factor methodology](https://12factor.net). This pull request extends the configuration to also include settings required to run doccano successfully behind an SSL terminating proxy. The change is fully backwards compatible since by default the new environment variables are disabled.
Example environment configuration to enable custom SSL:
```sh
export SESSION_COOKIE_SECURE="True"
export CSRF_COOKIE_SECURE="True"
export CSRF_TRUSTED_ORIGINS="some.domain.com"
```

Enhancement/Add settings required for SSL

---

app/authentification/tests/test_template.py
app/authentification/views.py

Email settings from custom settings module, configured via `DJANGO_SETTINGS_MODULE`, were ignored.

Fixes #309 read settings properly

---

README.md
cloudbuild.yaml

We were looking for an annotation tool and decided to go with yours, Nice work btw!
Given the following aspects:
- We are a very small team (<10 people)
- Cost should be as low as possible
- We annotate rather small datasets
We decided to go with GCP Run as a deployment solution, and it worked rather smoothly (thanks for having a Dockerfile ready)!  
Now, we are practically good to go, and our endpoint is up and running, but we were wondering if you think other people would be interested, given the aspects we just mentioned.
GCP Cloud Run is designed for stateless servers:
- Has a max RAM of 2GB
- Hard disk is not persistent among different deployments (i.e. once you deploy a new version, you will lose all data you have).
To do:
If you want to test `cloudbuild.yaml` link this repo to …

[discussion] GCP Run - "Free" deployment solution for small teams

---

.dockerignore
Dockerfile

This PR adds Hadolint, a Haskell Dockerfile linter, to doccano's Dockerfile which currently has a few Hadolint errors. 
1. Installs Hadolint v1.17.1
2. Runs Hadolint on /Dockerfile
3. Ignores two errors with inline `# hadolint ignore=[Error Code]` 
a. Ignore `Pin versions in apt-get install` where pinning a version on line 8 could cause build 
errors if the upstream node version changed.
b. Ignore `Pin versions in pip` due to a false positive on line 53 where installing wheels is 
already at a specific version.
As a result, upon building the Dockerfile there should be no Hadolint errors.
Collaboration with @c-w

Add linter for Dockerfile

---

frontend/components/organisms/projects/ProjectCreationForm.vue

In ver 1.0.0, I forgot to implement two options: randomize document order and share annotations across all users.

Add project creation options in new frontend

---

frontend/components/containers/annotation/TextClassification.vue

Now, we can annotate a text by shortcut keys in a text classification task.

Enable to use shortkeys in text classification and fix #453

---

Dockerfile
README.md

This pull request moves the SQLite database file used in Doccano's Dockerfile to a dedicated directory `/data` and binds this directory using a [VOLUME instruction](https://docs.docker.com/engine/reference/builder/#volume).
This enables us to persist Doccano's database file across container restarts in a filesystem/platform independent way. The README has been updated with instructions on how to leverage this functionality.
Resolves https://github.com/chakki-works/doccano/issues/438

Enhancement/Add volume for SQLite DB in doccano container

---

frontend/store/pagination.js

At first `checkpoint` localStorage entry does not exist, so
`checkpoint` variable ends up to be `null`.

Fix error on first annotation page open

---

app/app/settings.py
app/authentification/templates/acc_active_email.html
app/authentification/views.py
azuredeploy.json

In https://github.com/doccano/doccano/pull/250, @guillim introduced the ability for users to self-service sign-up for new Doccano accounts. This pull request ensures that the sign-up functionality works out-of-the-box in the Azure deployment which required a few changes:
1. Enabling configuring the email backend settings via environment variables so that deployments can turn on the feature without requiring a code change.
2. Removing hard-coded HTTP scheme the activation link sent in activation email so that the link also works on deployments that use HTTPS.
3. Adding a Sendgrid resource to the Azure deployment. By default this uses the free tier which covers 25,000 emails per month (see [pricing](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/SendGrid.SendGrid?tab=PlansAndP …

Enhancement/Verification emails on Azure

---

frontend/Dockerfile

There's an upstream issue with babel which affects node.js 13.1.0 (see: https://github.com/babel/babel/pull/11006 ) which prevents doccano from building (see #526), even when rolling back to v1.0.2.
This can be resolved by upgrading to node.js 13.2.0

Resolve build fail

---

app/api/tests/data/example_out_of_order_columns.csv
app/api/tests/test_api.py
app/api/utils.py

When uploading a CSV file for data import to Doccano, it's currently a requirement for the first column to be the text, the second column to be the label, and all the subsequent columns to be the metadata. This pull request relaxes this requirement and allows the columns to be provided in any order.
Resolves https://github.com/doccano/doccano/issues/510

Enhancement/Enable import of CSVs with arbitrary column order

---

nginx/nginx.conf

Consider environment where doccano is running on custom port. This can be easily done by changing host port in https://github.com/chakki-works/doccano/blob/d4b7c89647afa4d3f44e2b83aad4eb5ca59b2877/docker-compose.prod.yml#L32-L33
In this case `/projects` request (no slash at the end) will generate the following response:
```
$ curl -I localhost:4285/projects 2>/dev/null
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 27 Nov 2019 09:57:27 GMT
Content-Type: text/html
Content-Length: 162
Location: http://localhost/projects/
Connection: keep-alive
X-Frame-Options: DENY
```
Please note that custom port 4285 is not included in the `Location` header value.
Here is response with changes included in the PR:
```
$ curl -I localhost:4285/projects 2>/dev/null
HTTP/1.1 200 OK
Server: nginx …
```

Avoid redirects with custom port dropped

---

docs/faq.md

We should also remove `doccano_node_modules`, `doccano_venv` volumes on rebuild since doccano's dependencies could change.

Update rebuild FAQ

---

app/server/static/components/annotation.pug

- Display "Thumbs up" icon if the doc is approved.
- Else, display "Check mark" if the doc has annotations.
- Otherwise, display no icon.
See #280 for discussion.

Show  thumbs up icon for doc approved status on the left side view.

---

frontend/nuxt.config.js

As having this configured without a working backend will return dummy
data (projects) to the browser.
Fixes #789

Remove legacy endpoint

---

app/api/views.py

Add of requested feature from deathg0d from issue [#703 ](https://github.com/doccano/doccano/issues/703)
Annotation Approvers are now able to remove and edit any annotations from other annotators while annotators can only remove their own annotations.

change of permission for annotation edits

---

frontend/components/organisms/layout/TheSideBar.vue

Hey @Hironsan 
This fixes https://github.com/doccano/doccano/issues/621
I have added it in sidebar. PFB the images.

Added project name in sidebar

---

frontend/components/containers/annotation/EntityItemBox.vue
frontend/components/containers/annotation/Seq2seqContainer.vue
frontend/components/containers/annotation/TextClassification.vue
frontend/layouts/annotation.vue

Hi there,
First of all, I want to thank you warmly for all the work around doccano, this is an awesome project!
I had the same issue than #555 and #584 and wanted to see how to fix it. It appears indeed this is due to a delay when getting the new batch of documents, after reaching the 10 first documents cached in memory. 
I have made the document display dependent on the `state.loading` variable, making sure we do not display anything as long as the API call has not returned.
I don't know if you wanted to fix this issue this way ? Feel free to send feedback, I'll be happy to contribute further.

iss555: awaiting document loading before displaying text

---

app/requirements.txt

closes #858 
Because django-pyodbc-azure is inactive:
- https://github.com/michiya/django-pyodbc-azure/pull/204#issuecomment-563248221

Replace django-pyodbc-azure with django-mssql-backend

---

frontend/components/organisms/auth/LoginForm.vue

According to
- https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-change-users-or-admins-password
- https://github.com/doccano/doccano/issues/910#issuecomment-660893489
- #739 
- #723 
- #23 
login error means "Something went wrong" but not only "Incorrect username or password".

Info that login+password could be correct, too

---

app/api/tests/test_api.py
app/api/views.py

Now, if `share annotation` option is checked, all the roles can view/delete/update other's annotations.
Not realtime.
closes #705 
closes #629
closes #531

Allow annotator to update/delete other's annotations

---

app/api/serializers.py
app/api/views.py

closes #481 
This is a temporary solution. My thought:
https://github.com/doccano/doccano/issues/531#issuecomment-662185044

Fix ApproveLabelsAPI not to show other's annotations if it's checked

---

app/api/serializers.py

Minor change that adds additional fields to all of the `..Annotation` models' serializers to expose timestamp information in API query results.
Fixes #963.

Add timestamps to annotation serializers

---

template.aws.yaml

Now the AMI ID is dynamically set.
closes #975 
Ref:
- [Query for the latest Amazon Linux AMI IDs using AWS Systems Manager Parameter Store](https://aws.amazon.com/jp/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/)

Update cloudformation template to fix #957

---

frontend/components/containers/annotation/ApproveButton.vue
frontend/layouts/annotation.vue

Addressing issue #718
When user presses the ‘a’ key, the document toggles from ‘approved’ to ‘not approved’ or vice versa. The user is advanced to the next item in the queue once the key is pressed.

Adding keyboard shortcut for approval button

---

app/tools/run.sh
tools/run.sh

Noticed that the shell script `tools/run.sh` didn't include some echo statements and the workaround (`|| true`) for cases when the admin user exists, both of which exist in `app/tools/run.sh`.
This PR brings them both to parity.
Fixes #965.

Bring both run.sh scripts to parity

---

frontend/components/organisms/annotation/MultiClassClassification.vue

fix #942
I can't reproduce the 400 error so I only fixed the reset of the text.

Clear text in label selector after typing, fix #942

---

app/server/static/package-lock.json
app/server/static/package.json

Reverts doccano/doccano#1066
fix #1074 
fix #1083

Revert "Bump highlight.js from 9.12.0 to 10.1.2 in /app/server/static"

---

.github/workflows/pypi-publish.yml
MANIFEST.in
README.md
app/MANIFEST.in
app/doccano/doccano.py
app/setup.py
setup.py

To make doccano easy to use, this PR supports pip installation and allow doccano to run as a command line tool:
```bash
❯ pip install doccano
❯ doccano --port=8000
Starting server with port 8000.
[2020-12-04 12:00:26 +0900] [8255] [INFO] Starting gunicorn 19.9.0
[2020-12-04 12:00:26 +0900] [8255] [INFO] Listening at: http://0.0.0.0:8000 (8255)
[2020-12-04 12:00:26 +0900] [8255] [INFO] Using worker: sync
[2020-12-04 12:00:26 +0900] [8257] [INFO] Booting worker with pid: 8257
```
This is an experimental feature. The performance is not good because of using the development server.

Support pip Installation

---

app/api/views.py
frontend/components/containers/annotation/ApproveButton.vue
frontend/components/containers/annotation/ClearAnnotationsButton.vue
frontend/components/containers/annotation/EntityItemBox.vue
frontend/components/containers/annotation/FilterButton.vue
frontend/components/containers/annotation/GuidelineButton.vue
frontend/components/containers/documents/DocumentBulkDeletionButton.vue
frontend/components/organisms/utils/ConfirmForm.vue
frontend/i18n/en/generic.js
frontend/i18n/en/projects/dataset.js
frontend/layouts/annotation.vue
frontend/nuxt.config.js
frontend/pages/projects/_id/dataset/index.vue
frontend/services/annotation.service.js
frontend/services/document.service.js
frontend/store/documents.js

feat: "Delete All" and "Clear Annotations" buttons
- Added "Delete All" button to dataset view and "Clear Annotations" button to sequence-labeling view.
- Implemented DELETE methods for DocumentList and AnnotationList in API to allow deletion of multiple objects with a single HTTP request.
The location of the "Clear Annotations" button can be improved somewhat. Moreover, a confirmation dialog is not used to confirm the user's intent.
"Delete All" button:
"Clear Annotations" button:
Resolves: #523, #631

Clear annotations and bulk delete functionality. (Fix #523 and #631)

---

app/doccano/doccano.py

This is PR improved the python3 compatibility problem. Previously, it calls the python executable in the environment. This could be troublesome since many linux system has python2 as default executable in the environment, but the user might installed the python3 version of the package.
Changing 'python' to sys.executable would force the executable for django to be the same as doccano.

fix python3 compatibility problem

---

docs/faq.md

admin panel url is a path, not a file
see https://github.com/doccano/doccano/issues/1205

fix missleading admin path example in faq

---

app/api/tests/data/example.csv
app/api/tests/test_api.py

Prototype of a new test that checks whether importing and exporting the same data preserves integrity.
Current upload/download tests only check for http response codes.

Add Import-Export-Integrity-Tests

---

frontend/domain/models/document/format.ts

Many users reported that the wrong output occurs during exporting to the jsonl(textlabel) format. I investigated the error and think its because of a typo error in the format.ts file. 
See (#1267) for reference. Maybe also (#1257)

Fixed jsonl type error

---

README.md

See diffs. This md file goes through the setup process using pip. However, it says to use `doccano webserver -p 8000`, but the parameter -p is not valid. You must use --port instead. That's what I have changed.

Changed "doccano webserver -p" argument to "--port"

---

README.md

Temporarily stopping Azure support:
- The one-click deployment has been failed for a long time.
- The pull requests to fix the problem have not been sent for a long time.
close https://github.com/doccano/doccano/issues/931
close https://github.com/doccano/doccano/issues/1153
close https://github.com/doccano/doccano/issues/1215
close https://github.com/doccano/doccano/issues/1226
close https://github.com/doccano/doccano/issues/1297
close https://github.com/doccano/doccano/issues/1308

Stop Azure Support

---

backend/api/views/download/writer.py

download dataset to a csv file, but I get an empty file in zip
download json file or jsonL file contains chinese, it shows \uxxxx but not chinese

fix download dataset problems

---

backend/api/views/auto_labeling.py

This a PR to fix part of the issues from #1307, which caused failures when trying to create Custom REST Request models.

Remove unneeded builder call

---

frontend/components/layout/TheSideBar.vue
frontend/domain/models/project/project.ts
frontend/layouts/project.vue
frontend/layouts/workspace.vue
frontend/pages/projects/_id/labels/index.vue
frontend/pages/projects/_id/links/index.vue
frontend/services/application/project/projectData.ts

Depending on the project type, we don't need to show label and relation item in the sidebar.
This PR hides them depending on the project type.

Hide label and relation from the sidebar

---

README.md
config/.env.example
docker-compose.dev.yml
docker-compose.prod.yml

I think it would be more convenient regarding git updates to extract the config variables from docker-compose files into an .env file as demonstrated in the [docker documentation](https://docs.docker.com/compose/environment-variables/).

put variables to .env file

---

frontend/components/tasks/metadata/ListMetadata.vue

feature_request from [issue-1067](https://github.com/doccano/doccano/issues/1067)
- display image when the key is `"im_url"`, for example: `"im_url": "http://media-prod.oxfam.org.uk/images/products/HighStDonated/Main/HD_101670797_01.jpg"`
- create a link when the key contains string `"url"`, for example: `"product_url"`. (since the logic is to always handle `"im_url"` first, thus even though `"im_url"` also contains string `"url"`, it won't be handled here)
You can try out using these jsonl:
```json
{"text": "[title] Drownproofing\n[desc] Describes a survival technique designed to keep you afloat indefinitely (well, at least until you grow old and die of natural causes). With this concept of water safety anyone - young or old or even the non-swimmer can be virtually insured against …
```

support image display and url handling

---

frontend/components/layout/TheSideBar.vue
frontend/middleware/check-admin.js
frontend/pages/projects/_id/dataset/index.vue

https://github.com/doccano/doccano/issues/952
- Allow dataset list page to be displayed not only for admin users but also for annotators and approvers.
- Hide the import, download, and delete action buttons except for admin.
Annotator's screen
- Add a column to indicate the status of the annotation.

Display dataset page for all user

---

backend/api/tests/download/test_writer.py
backend/api/views/download/data.py
backend/api/views/download/writer.py

Update CsvWriter to fix repeated metadata column when exported as csv

---

frontend/components/tasks/toolbar/buttons/ButtonReview.vue

It seems like the "enter" key keyboard shortcut for the accept/review button functionality was lost at some point. See discussion in  #718 and issue #1398. This pull request restores the functionality

Add keyboard shortcut back to accept button

---

backend/api/models.py
backend/api/tests/api/utils.py
backend/api/tests/test_models.py
backend/api/views/annotation.py
frontend/components/tasks/sequenceLabeling/EntityEditor.vue
frontend/pages/projects/_id/sequence-labeling/index.vue
frontend/services/application/tasks/annotationApplicationService.ts
frontend/services/application/tasks/sequenceLabeling/sequenceLabelingApplicationService.ts

Update unique constraint of Span

---

backend/api/tests/api/test_comment.py
backend/api/views/comment.py
frontend/components/comment/CommentList.vue
frontend/domain/models/comment/comment.ts
frontend/domain/models/comment/commentRepository.ts
frontend/pages/projects/_id/comments/index.vue
frontend/repositories/comment/apiCommentRepository.ts
frontend/services/application/comment/commentApplicationService.ts
frontend/services/application/comment/commentData.ts

The speed of fetching the comment list was slow due to the fact it fetches all the examples at the same time. This PR stops fetching the examples and speeds up fetching comments.
Note that the feature of moving to the annotation page from the comment list page is temporarily stopped. This will be resolved in future PR.

Speed up fetching comment

---

backend/api/tests/api/test_annotation.py
backend/api/urls.py
backend/api/views/tasks/base.py
backend/api/views/tasks/category.py
backend/api/views/tasks/span.py
backend/api/views/tasks/text.py
frontend/repositories/tasks/seq2seq/apiSeq2seq.ts
frontend/repositories/tasks/sequenceLabeling/apiSequenceLabeling.ts
frontend/repositories/tasks/textClassification/apiTextClassification.ts

Currently, there is an endpoint to annotate data(`/annotations`). This is not useful for some tasks like #617 and relation extraction(this requires NER and relation labeling at the same time).
The new endpoints are divided into three separate ones:
- `/categories`
- `/spans`
- `/texts`

[Enhancement] Refactor Annotation API

---

backend/api/models.py
backend/api/serializers.py
backend/api/views/auto_labeling.py
frontend/domain/models/project/project.ts

[Enhancement] refactor project model and serializer

---

frontend/components/tasks/sequenceLabeling/LabelingMenu.vue

Currently labeling two entities with the same label by choosing it from the
autocomplete, didn't work. Labeling the first entity worked, but when you
tried to label a new entity with the same label chosen from the
autocomplete, nothing happened.

Fix state of label selection on LabelingMenu for sequenceLabeling

---

backend/api/migrations/0017_example_uuid.py

This is a fix for #1595.
What happened was that if there was data in the DB, a single uuid4 value would be created, so the migration would fail because of the unique constraint. 
The change is to first create the field, without a unique constraint and with null values, run a Python function to create uuid4s for each Example, and then change the field to have the unique constraints.

Fix migration when adding uuids

---

backend/data_export/pipeline/catalog.py
backend/data_export/pipeline/data.py
backend/data_export/pipeline/repositories.py
backend/data_export/tests/test_writer.py
backend/data_import/pipeline/parsers.py
backend/label_types/tests/test_models.py
backend/labels/migrations/0008_auto_20220222_0630.py

- Remove unused variables
- Rename parameter names because they use built-in names(id, format)

[Enhancement] Fix minor code issues

---

docs/tutorial.md

Update tutorial document

---

backend/data_import/pipeline/writers.py

https://github.com/doccano/doccano/issues/1720
Bug fix: Specify project when retrieving labels in celery task

Bug fix: Specify project when retrieving labels in celery task

---

.github/workflows/pypi-publish.yml
docker/Dockerfile
docker/Dockerfile.nginx

Fix the following error:
```bash
The unauthenticated git protocol on port 9418 is no longer supported.
```
Related to:
- https://github.blog/2021-09-01-improving-git-protocol-security-github/

Replace git:// with https://

---

frontend/yarn.lock

Fixes: ```The unauthenticated git protocol on port 9418 is no longer supported.```

fix: Replace git:// with https:// in yarn.lock

---

tools/azure.sh
tools/create-admin.sh
tools/create-package.sh
tools/dev-celery.sh
tools/dev-django.sh
tools/dev-nuxt.sh
tools/heroku.sh
tools/install-mssql.sh
tools/prod-celery.sh
tools/prod-django.sh
tools/run.sh

Trying to fix #860 in wider manner.
Check need...

Set nounset on Bash scripts (fixes #860)

---

backend/metrics/tests.py
backend/metrics/views.py

show total progress if collaborative_annotation

---

backend/data_import/celery_tasks.py
backend/data_import/datasets.py
backend/data_import/pipeline/catalog.py
backend/data_import/pipeline/exceptions.py
backend/data_import/pipeline/factories.py
backend/data_import/pipeline/label.py
backend/data_import/pipeline/label_types.py
backend/data_import/tests/test_label.py
backend/data_import/tests/test_label_types.py
backend/data_import/tests/test_tasks.py

- Add non-negative constraint to span offset
- Add non-empty constraint to label type names
- Replace `get_by_text` with `__getitem__`
- Replace file format string with `Format` class

[Refactoring] data import

---

frontend/components/tasks/toolbar/ToolbarLaptop.vue
frontend/components/tasks/toolbar/buttons/ButtonKeyboardShortcut.vue
frontend/components/tasks/toolbar/forms/FormKeyboardShortcut.vue

[Enhancement] keyboard shortcut

---

frontend/i18n/de/rules.js
frontend/i18n/fr/rules.js
frontend/i18n/zh/rules.js

regarding #1175, max upload size was increased  from 1MB to 100 MB.
But, only English message was fixed.  
```
de/rules.js:    fileLessThan1MB: 'Dateigröße muss kleiner als 1 MB sein!'
en/rules.js:    fileLessThan1MB: 'File size should be less than 100 MB!'
fr/rules.js:    fileLessThan1MB: 'La taille du fichier doit être inférieure à 1MB'
zh/rules.js:    fileLessThan1MB: '文件大小必须小于 1 MB!'
```

fix de, fr and zh messages

---

frontend/pages/projects/_id/sequence-labeling/index.vue

Expected behavior:
After checked, then it will not post the auto labeling url.
Implemented the behavior.

Fixed  #1816

---

docs/developer_guide.md

In the developer guide section at the end of the backend the link that
redirects to the `installation guide` was displaying : 404 - Not found

fix: install guide not acessible in the documentation website.

---

docker/Dockerfile
docker/Dockerfile.nginx
docker/Dockerfile.prod

The EOL date of buster is 2022/08. So update to bullseye.
- [Debian Releases](https://wiki.debian.org/DebianReleases)

Update buster to bullseye

---

docker/docker-compose.prod.yml

The EOL date of RabbitMQ 3.8 is 2022/07/31. So update to 3.10.
- [Release Series | RabbitMQ](https://www.rabbitmq.com/versions.html)

Update RabbitMQ version

---

docker/Dockerfile.nginx
docker/docker-compose.prod.yml
docker/nginx/nginx.conf.template

- Enable to change the worker processes for Nginx
- Specify a number or `auto` to `WORKER_PROCESSES` 
- The default value is `auto`

Enable to set worker processes by environment variable

---

docs/developer_guide.md

| Environment Variable   | Description                                                                                                                                                                                                                                                                                               |
| ---------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| SECRET_KEY             | A secret key for a particular doccano installation. This is used to provide [cryptographic …

Describe the environment variables

---

frontend/pages/projects/index.vue

Fix the following problem:
```bash
#16 244.0 ERROR in pages/projects/index.vue:57:55
#16 244.0 TS2345: Argument of type 'Dictionary<string | (string | null)[]>' is not assignable to parameter of type 'SearchQueryData'.
#16 244.0   Type 'Dictionary<string | (string | null)[]>' is missing the following properties from type 'SearchQueryData': limit, offset
#16 244.0     55 |   async fetch() {
#16 244.0     56 |     this.isLoading = true
#16 244.0   > 57 |     this.projects = await this.$services.project.list(this.$route.query)
#16 244.0        |                                                       ^^^^^^^^^^^^^^^^^
#16 244.0     58 |     this.isLoading = false
#16 244.0     59 |   },
#16 244.0     60 |
#16 244.0 
#16 244.0  FATAL  Nuxt build error
```

Fix nuxt build problem

---

backend/auto_labeling/exceptions.py
backend/auto_labeling/views.py

Showed a bit better message:
Before:
After:

Handle JSONDecodeError on testing auto labeling API

---

backend/cli.py

fix #2086 
fix #2072 
fix #2073 
fix #2080

Update cli to avoid ValueError: path must be a filename, not a directory.

---

frontend/store/projects.js

Currently, `setCurrent` method converts `Project` into an object. As a result, some method like `isImageProject` cannot be used. This PR fixes the problem.

Fix project store to use Project model

---

docs/faq.md
docs/index.md
docs/tutorial.md

Fix formatting of doccano docs. 
- Fix formatting of text, code snippets in Index, FAQ, Tutorial in an ordered list (two tabs for images, two tabs for code snippets, no backticks for codeblocks included in an ordered list)
- Fix broken link to FAQ 
Note: When making changes for https://github.com/doccano/doccano/pull/2216, local markdown preview rendered markdown differently than published mkdocs. This time, used mkdocs locally to test/verify that changes render correctly.

Fix appearance of lists in doccano docs

---

backend/cli.py
backend/data_import/pipeline/label.py
backend/poetry.lock
backend/projects/models.py
backend/pyproject.toml

Update pydantic version

---

backend/config/settings/gcp.py

The variable can often be omitted in environments that use default credentials such as GKE (Google cloud's managed Kubernetes) or VM instances.
Django-storages also acknowledges this, and it provides GS_CREDENTIALS as a way around systems where the default credentials are not used or undesired.
However, it's impossible to not set the environment variable setting, and without passing a path to a valid file that contains a valid JSON structure of a service account key, this code will raise an error.
Refs:
* https://django-storages.readthedocs.io/en/latest/backends/gcloud.html#authentication-settings
* https://googleapis.dev/python/google-auth/latest/reference/google.auth.html#google.auth.default
* https://github.com/googleapis/google-auth-library-python/blob/d2ab3afdb567850121fec7de1d86fb5fb …

fix: make GOOGLE_APPLICATION_CREDENTIALS optional

---

backend/data_import/pipeline/label.py

In file: label.py, class: `Label`, there is a special method `__lt__` that raises a `NotImplementedError`. If a special method supporting a binary operation is not implemented it should return `NotImplemented`. On the other hand, `NotImplementedError` should be raised from abstract methods inside user defined base classes to indicate that derived classes should override those methods. I suggested that the special method `__lt__` should return `NotImplemented` instead of raising an exception. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project …

Update an incorrectly implemented method

---

docker/docs_docker-quickstart_Version2.md

This PR adds a new documentation file, `docker/docs_docker-quickstart_Version2.md`, which provides clear, step-by-step instructions for running doccano using Docker and Docker Compose. The guide includes:
- How to build and start all necessary services (backend, frontend, Celery worker, Redis) with Docker Compose
- Creating a superuser using Docker
- Ensuring that the Celery worker is running so that the export functionality works
- Troubleshooting tips for export issues
This documentation is intended to help new users and contributors set up a working doccano environment quickly, especially those who rely on Docker for development and deployment.
If you have any suggestions or would like further clarification in the docs, please let me know!

docs: add Docker quickstart guide
